### ISSUE TITLE
Motion sensors wrongly labeled in HAP-NodeRed

### ISSUE THREAD

**Issue by bohtho** [NorthernMan54/HAP-NodeRed#2]
Just updated to 0.0.39 and noticed my (IKEA trådfri) motion sensors are labeled in the node with "[a date and time] - Motion sensor" whereas other accessories are labeled with "[their name] - [Accessory type]".

**Comment by NorthernMan54** [comment]
Please update to the latest and try again.

**Comment by bohtho** [comment]
Perfect.

**Comment by NorthernMan54** [comment]
![Screen Shot 2020-01-29 at 11 10 11 PM](https://user-images.githubusercontent.com/19808920/73419506-5d67fd80-42ed-11ea-8a54-3114ff23692c.png)
