### ISSUE TITLE
Lots of ` hapNodeJSClient HAP Discover failed Node-RED` for weird ports

### ISSUE THREAD

**Issue by iRonin** [NorthernMan54/HAP-NodeRed#4]
I have a lot of the following errors:

```
hapNodeJSClient HAP Discover failed Node-RED http://x.x.x.x:35026 invalid PIN or homebridge is not running in insecure mode with -I IncomingMessage { | stdout
```

For some reason it tries to connect to those weird ports: 42980, 35026; while my HB runs on standard 51826 and the integration partially works - I'm trying to debug why certain sensors are not triggered inside NR.

**Comment by NorthernMan54** [comment]
Do you have native HomeKit devices?  It could be them, and the messages can be ignored.

For the sensor, if you leave the home app open with the sensor visible, and you trigger the sensor does the icon change in real time? That is the event that is sent to the hub-event node.

If you run in debug mode it is a bit verbose, but it will show registering the events, and the actual event.  Sometimes I find restarting node-red fixes things.

**Comment by iRonin** [comment]
I'm sorry, @NorthernMan54, it was a dead battery in a sensor :)

However, it would be great to limit this logging to maybe one line for failed Discovery - currently, it logs dozen of lines and it's clogging the log. Maybe use different logging level for debugging and log only 1 line with `warn`?

**Comment by NorthernMan54** [comment]
Unfortunately I'm using DEBUG, which does not support different levels, only on or off ;-(
